---
spring:
 application: 
  name: praveen-spring-cloud-config-server

 cloud:
   config:
     server:
       git:
        uri: https://github.com/praveenoruganti/praveen-spring-config-server
        searchPaths: config
        
        

server:
 port: 8888

