spring:
 h2:
    console:
      enabled: true
 jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format-sql: true
logging:
   level:
     org:
      hibernate:
        stat: debug
        type: debug

server:
  port: 9080